baseURL = "https://tailwind-elements.com/"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "ga-hugo-theme"
enableInlineShortcodes = "true"
custom_css = ["css/custom.css"]

# NODE_ENV=production hugo
